# Generated by Django 6.1 on 2026-09-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('inventory', '0004_merge_20260818_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requested_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_requests', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='event',
            name='requested_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
