# Generated by Django 6.1.1 on 2026-09-05 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_status'),
        ('inventory', '0004_merge_20260818_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='events.event')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_allocations', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-allocated_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'item'), name='unique_event_resource')],
            },
        ),
    ]
