# Generated by Django 6.1.1 on 2026-09-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventformlink'),
        ('events', '0004_eventresource'),
    ]

    operations = [
    ]
