# Generated by Django 6.1.1 on 2026-09-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_merge_0003_eventformlink_0004_eventresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_scheduled_date',
            field=models.DateField(blank=True, help_text='Configured notification trigger date', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Automated reminder sent to organizers and volunteers'),
        ),
    ]
