# Generated by Django 6.1.1 on 2026-09-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_reminder_scheduled_date_event_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('EVENT', 'Event'), ('CAMPAIGN', 'Campaign')], db_index=True, default='EVENT', max_length=20),
        ),
    ]
