# Generated by Django 6.1.1 on 2026-09-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='consent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_ref',
            field=models.CharField(blank=True, help_text='Physical consent form ID or digital verification reference', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='parental_consent_obtained',
            field=models.BooleanField(default=False, help_text='Parental/Guardian DPDP consent recorded for minor student data collection'),
        ),
    ]
