# Generated by Django 6.1 on 2026-08-17 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_school_affiliation_school_established_date_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Aequs Aerospace Precision Engineering Internship', max_length=200)),
                ('program_code', models.CharField(help_text='e.g. AEQ-INT-2026-01', max_length=50, unique=True)),
                ('company_name', models.CharField(default='Aequs Aerospace SEZ', max_length=150)),
                ('department', models.CharField(choices=[('AEROSPACE_ENG', 'Aerospace Engineering'), ('PRECISION_MANUFACTURING', 'Precision Manufacturing & CNC'), ('QUALITY_ASSURANCE', 'Quality Assurance & Metrology'), ('IT_AND_SOFTWARE', 'Information Technology & Systems'), ('SUPPLY_CHAIN', 'Supply Chain & Logistics'), ('TOOL_AND_DIE', 'Tool & Die Making'), ('FINANCE_OPERATIONS', 'Finance & Commercial Operations'), ('HUMAN_RESOURCES', 'Human Resources & CSR'), ('OTHER', 'General / Technical Operations')], default='PRECISION_MANUFACTURING', max_length=50)),
                ('location', models.CharField(default='Belagavi SEZ, Karnataka', max_length=150)),
                ('duration_months', models.PositiveIntegerField(default=3, help_text='Duration in months')),
                ('stipend_amount', models.DecimalField(decimal_places=2, default=8000.0, help_text='Monthly stipend in INR', max_digits=10)),
                ('total_slots', models.PositiveIntegerField(default=15, help_text='Maximum candidate capacity')),
                ('academic_year', models.CharField(default='2026-27', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, default='Degree / Diploma / Vocational candidates with technical or science background.')),
                ('description', models.TextField(blank=True)),
                ('mentor_in_charge', models.CharField(blank=True, max_length=150)),
                ('mentor_contact', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open for Applications'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed / Archived')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Internship Program',
                'verbose_name_plural': 'Internship Programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2026-27', max_length=20)),
                ('department', models.CharField(choices=[('AEROSPACE_ENG', 'Aerospace Engineering'), ('PRECISION_MANUFACTURING', 'Precision Manufacturing & CNC'), ('QUALITY_ASSURANCE', 'Quality Assurance & Metrology'), ('IT_AND_SOFTWARE', 'Information Technology & Systems'), ('SUPPLY_CHAIN', 'Supply Chain & Logistics'), ('TOOL_AND_DIE', 'Tool & Die Making'), ('FINANCE_OPERATIONS', 'Finance & Commercial Operations'), ('HUMAN_RESOURCES', 'Human Resources & CSR'), ('OTHER', 'General / Technical Operations')], default='PRECISION_MANUFACTURING', max_length=50)),
                ('company_name', models.CharField(default='Aequs Aerospace SEZ', max_length=150)),
                ('project_title', models.CharField(blank=True, help_text='e.g. CNC Machine Calibration & Quality Tolerance Optimization', max_length=200)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('stipend_amount', models.DecimalField(decimal_places=2, default=8000.0, help_text='Monthly stipend in INR', max_digits=10)),
                ('mentor_name', models.CharField(blank=True, max_length=150)),
                ('mentor_email', models.EmailField(blank=True, max_length=254)),
                ('mentor_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied / Nominated'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWING', 'Interview Scheduled'), ('SELECTED', 'Selected / Active'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed Successfully'), ('WITHDRAWN', 'Withdrawn'), ('TERMINATED', 'Terminated')], default='SELECTED', max_length=20)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=5, null=True)),
                ('performance_grade', models.CharField(choices=[('OUTSTANDING', 'Outstanding (A+)'), ('EXCELLENT', 'Excellent (A)'), ('VERY_GOOD', 'Very Good (B+)'), ('GOOD', 'Good (B)'), ('SATISFACTORY', 'Satisfactory (C)'), ('PENDING', 'Evaluation Pending')], default='PENDING', max_length=20)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('certificate_issue_date', models.DateField(blank=True, null=True)),
                ('evaluation_feedback', models.TextField(blank=True, help_text='Supervisor performance remarks & learning milestones achieved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_placements', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_placements', to='students.student')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='internships.internshipprogram')),
            ],
            options={
                'verbose_name': 'Internship Placement',
                'verbose_name_plural': 'Internship Placements',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Week 4: CAD Blueprint Modelling & Simulation', max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'Under Mentor Review'), ('APPROVED', 'Approved / Completed'), ('NEEDS_REVISION', 'Needs Revision')], default='PENDING', max_length=20)),
                ('deliverables_url', models.URLField(blank=True, help_text='Link to reports or project repository')),
                ('mentor_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='internships.internshipplacement')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
