# Generated by Django 6.0.4 on 2026-09-05 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume'), ('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('COLLEGE_ID', 'College ID'), ('BONAFIDE', 'Bonafide Certificate'), ('MARKSHEET', 'Marksheet'), ('OFFER_LETTER', 'Offer Letter'), ('OTHER', 'Other Document')], max_length=30)),
                ('document', models.FileField(upload_to='internship_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='internships.internshipplacement')),
            ],
            options={
                'verbose_name': 'Internship Document',
                'verbose_name_plural': 'Internship Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
