# Generated by Django 6.1.1 on 2026-09-11 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_internshipdocument'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipplacement',
            name='linked_program',
            field=models.ForeignKey(blank=True, help_text='Linked Program under EduTrack', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='programs.program'),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Linked Project under EduTrack Programs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='programs.project'),
        ),
        migrations.AddField(
            model_name='internshipprogram',
            name='linked_program',
            field=models.ForeignKey(blank=True, help_text='Linked Program under EduTrack', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_programs', to='programs.program'),
        ),
        migrations.AddField(
            model_name='internshipprogram',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Linked Project under EduTrack Programs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_programs', to='programs.project'),
        ),
    ]
