# Generated by Django 6.1.1 on 2026-09-05 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteeractivity_eventparticipation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Associated user account if the volunteer has login access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='participation_status',
            field=models.CharField(choices=[('REQUESTED', 'Requested (Pending Approval)'), ('ASSIGNED', 'Assigned'), ('ATTENDED', 'Attended'), ('ABSENT', 'Absent'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=20),
        ),
    ]
