# Generated by Django 6.1.1 on 2026-10-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_volunteerformlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150)),
                ('employee_role', models.CharField(blank=True, default='Aequs Volunteer', max_length=150)),
                ('department', models.CharField(blank=True, default='Aerospace Operations', max_length=150)),
                ('plant_location', models.CharField(blank=True, default='Belagavi SEZ', max_length=150)),
                ('quote', models.TextField(help_text='Personal reflection or impact statement about volunteering')),
                ('video_url', models.CharField(blank=True, default='', help_text='YouTube embed, Vimeo, or direct MP4 link', max_length=500)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='testimonials/videos/')),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=500)),
                ('academic_year', models.CharField(default='2026-27', max_length=20)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Employee Testimonial',
                'verbose_name_plural': 'Employee Testimonials',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
