# Generated by Django 6.0.4 on 2026-08-12 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('BOOK', 'Books'), ('WORKBOOK', 'Workbook'), ('STUDY_KIT', 'Study Kit')], max_length=30)),
                ('academic_year', models.CharField(help_text='Example: 2026-27', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('distribution_date', models.DateField(auto_now_add=True)),
                ('issued_by', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='students.student')),
            ],
            options={
                'ordering': ['-distribution_date'],
            },
        ),
    ]
