# Generated by Django 6.1 on 2026-08-13 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0001_initial'),
        ('inventory', '0003_inventoryitem_stocktransaction'),
        ('schools', '0002_school_affiliation_school_established_date_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Primary STEM Kit, High School Kit, PUC Science Kit', max_length=200, unique=True)),
                ('target_grade_level', models.CharField(default='Class 1 to 2nd PUC', help_text='e.g. Class 1-5, Class 6-10, 1st PUC & 2nd PUC', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ['-distribution_date', '-created_at'], 'verbose_name': 'Distribution Record', 'verbose_name_plural': 'Distribution Records'},
        ),
        migrations.AddField(
            model_name='distribution',
            name='essential_item_type',
            field=models.CharField(blank=True, choices=[('BENCHES', 'Benches'), ('DESKS', 'Desks'), ('CHAIRS', 'Chairs'), ('WHITE_BOARDS', 'White Boards'), ('LIBRARY_BOOKS', 'Library Books'), ('LAB_EQUIPMENT', 'Laboratory Equipment'), ('WATER_FILTERS', 'Water Filters'), ('FANS', 'Fans'), ('SPORTS_KITS', 'Sports Kits'), ('PROJECTORS', 'Projectors'), ('OTHER', 'Other Educational Resources')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='recipient_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('SCHOOL', 'Government School')], default='STUDENT', max_length=20),
        ),
        migrations.AddField(
            model_name='distribution',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_distributions', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='academic_year',
            field=models.CharField(default='2026-27', help_text='Example: 2026-27', max_length=20),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='benefit_type',
            field=models.CharField(choices=[('BOOK', 'Books'), ('WORKBOOK', 'Workbook'), ('STUDY_KIT', 'Study Kit'), ('LAPTOP', 'Laptop'), ('SCHOOL_ESSENTIAL', 'Government School Essential')], max_length=30),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distribution_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='students.student'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='study_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='distributions.studykit'),
        ),
        migrations.CreateModel(
            name='StudyKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='e.g. Geometry Box, 6 Long Notebooks, Drawing Pad, Color Pencils', max_length=150)),
                ('quantity_per_kit', models.PositiveIntegerField(default=1)),
                ('specification', models.CharField(blank=True, max_length=200)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='distributions.studykit')),
            ],
        ),
    ]
