# Generated by Django 6.0.4 on 2026-08-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='benefit_type',
            field=models.CharField(choices=[('BOOK', 'Books'), ('WORKBOOK', 'Workbook'), ('STUDY_KIT', 'Study Kit'), ('LAPTOP', 'Laptop')], max_length=30),
        ),
    ]
