# Generated by Django 6.0.4 on 2026-08-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0002_alter_distribution_benefit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='benefit_type',
            field=models.CharField(choices=[('BOOK', 'Books'), ('WORKBOOK', 'Workbook'), ('STUDY_KIT', 'Study Kit'), ('LAPTOP', 'Laptop'), ('INTERNSHIP', 'Internship')], max_length=30),
        ),
    ]
