# Generated by Django 6.1 on 2026-08-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0002_studykit_alter_distribution_options_and_more'),
        ('distributions', '0003_alter_distribution_benefit_type'),
    ]

    operations = [
    ]
