# Generated by Django 6.1.1 on 2026-09-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0004_merge_20260818_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Distribution location e.g. Belagavi SEZ, Kittur Campus', max_length=200),
        ),
    ]
