# Generated by Django 6.1.1 on 2026-09-05 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_must_change_password'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='VOLUNTEER', max_length=50),
        ),
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether users with this role have administrative portal privileges.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(blank=True, help_text='Underlying permission group automatically linked to this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_role', to='auth.group')),
            ],
            options={
                'verbose_name': 'System Role',
                'verbose_name_plural': 'System Roles',
                'ordering': ['name'],
            },
        ),
    ]
