# Generated by Django 6.0.4 on 2026-08-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('REPLACED', 'Replaced')], default='ISSUED', max_length=20)),
                ('issue_notes', models.TextField(blank=True)),
                ('return_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventory.laptop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laptop_assignments', to='students.student')),
            ],
        ),
    ]
