# Generated by Django 6.0.4 on 2026-08-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_laptopassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('RETIRED', 'Retired'), ('REPLACED', 'Replaced')], default='AVAILABLE', max_length=20),
        ),
    ]
