# Generated by Django 6.1 on 2026-08-13 05:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_laptopassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('sku', models.CharField(help_text='Stock Keeping Unit / Item Code', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('BOOKS', 'Books'), ('WORKBOOKS', 'Workbooks'), ('STUDY_KITS', 'Study Kits'), ('LAPTOPS', 'Laptops'), ('SCHOOL_ESSENTIALS', 'School Essentials'), ('EVENT_MATERIALS', 'Event Materials')], default='BOOKS', max_length=30)),
                ('unit', models.CharField(default='Pieces', help_text='Unit of measurement (e.g. Pieces, Sets, Packs, Units)', max_length=50)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Alert triggered when stock falls at or below this level')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, help_text='Warehouse / Room / Shelf location', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['category', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('ADJUSTMENT', 'Stock Adjustment')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('source_destination', models.CharField(blank=True, help_text='Supplier/Vendor (for Stock In) or School/Student/Event (for Stock Out)', max_length=200)),
                ('reference_number', models.CharField(blank=True, help_text='PO / Invoice / Dispatch Ref / Voucher #', max_length=100)),
                ('performed_by', models.CharField(blank=True, max_length=150)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
