# Generated by Django 6.1 on 2026-08-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_laptop_status'),
        ('inventory', '0003_inventoryitem_stocktransaction'),
    ]

    operations = [
    ]
