# Generated by Django 6.0.4 on 2026-09-04 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('STUDENT', 'Student'), ('SCHOOL', 'School'), ('ELIGIBILITY', 'Eligibility'), ('INVENTORY', 'Inventory'), ('DISTRIBUTION', 'Distribution'), ('LAPTOP', 'Laptop'), ('STUDY_KIT', 'Study Kit'), ('AUTH', 'Authentication'), ('USER', 'User'), ('REPORT', 'Report')], default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
