# Generated by Django 6.1.1 on 2026-09-05 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('STUDENT_DEMOGRAPHICS', 'Student Demographics & Enrollment'), ('BENEFIT_ELIGIBILITY', 'Benefit Eligibility (Kits, Laptops, Books)'), ('DISTRIBUTION_SUMMARY', 'Inventory & Distribution Records'), ('SCHOOL_INFRASTRUCTURE', 'School Infrastructure & Reach'), ('ACTIVITY_AUDIT', 'System Activity & Audit Logs'), ('CUSTOM', 'Custom Operational Report')], default='STUDENT_DEMOGRAPHICS', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.CharField(blank=True, help_text='e.g. 2024-2025 or leave blank for all years', max_length=30, null=True)),
                ('category_filter', models.CharField(blank=True, help_text='Optional category or benefit type filter', max_length=50, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'All Users (Public)'), ('ROLES', 'Specific System Roles'), ('GROUPS', 'Specific User Groups'), ('CREATOR', 'Private (Only Me & Super Admins)')], default='PUBLIC', max_length=20)),
                ('allowed_roles', models.CharField(blank=True, default='', help_text='Comma-separated role codes e.g. SUPER_ADMIN,ADMIN,ACCOUNTANT', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Groups permitted to view this report', related_name='accessible_reports', to='auth.group')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
