# Generated by Django 6.1.1 on 2026-09-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, help_text='Attach PDF report, signed documentation, or supporting files', null=True, upload_to='reports/attachments/'),
        ),
        migrations.AddField(
            model_name='report',
            name='row_limit',
            field=models.PositiveIntegerField(default=100, help_text='Maximum records to include (0 for all matching records)'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft / In Review'), ('PUBLISHED', 'Published / Final'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='summary_notes',
            field=models.TextField(blank=True, help_text='Executive summary, audit findings, or custom commentary'),
        ),
    ]
