# Generated by Django 6.1.1 on 2026-09-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_attachment_report_row_limit_report_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='row_limit',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Maximum records to include (0 for all matching records)', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft / In Review'), ('PUBLISHED', 'Published / Final'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20),
        ),
    ]
