# Generated by Django 6.1.1 on 2026-09-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_activitylog_action_type_and_more'),
        ('reports', '0004_alter_report_row_limit_alter_report_status'),
    ]

    operations = [
    ]
