# Generated by Django 6.1 on 2026-08-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_affiliation_school_established_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradestrength',
            name='student_names',
            field=models.TextField(blank=True, default=''),
        ),
    ]
