# Generated by Django 6.1.1 on 2026-09-11 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('students', '0002_student_consent_date_student_consent_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Facility, campus, school center or venue name', max_length=200)),
                ('code', models.CharField(help_text='e.g. LOC-BGV-01', max_length=50, unique=True)),
                ('district', models.CharField(default='Belagavi', max_length=100)),
                ('taluk', models.CharField(blank=True, default='', max_length=100)),
                ('village_or_town', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.AddField(
            model_name='scholarship',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Linked Program (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to='programs.program'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Linked Project (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to='programs.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, help_text='e.g. PRJ-2026-001 (auto-generated if left blank)', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='Multi-select operational locations', related_name='programs', to='programs.location'),
        ),
        migrations.AddField(
            model_name='project',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='Select one or more operational locations', related_name='projects', to='programs.location'),
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(help_text='e.g. 1-on-1 Engineering Mentoring, Career Guidance', max_length=200)),
                ('session_code', models.CharField(blank=True, help_text='e.g. MNT-2026-001 (auto-generated)', max_length=50, unique=True)),
                ('mentor_name', models.CharField(help_text='Corporate mentor or Foundation advisor', max_length=150)),
                ('mentor_email', models.EmailField(blank=True, max_length=254)),
                ('mentor_designation', models.CharField(blank=True, default='Aequs Corporate Mentor', max_length=150)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('topic', models.CharField(help_text='Curriculum topic, technical guidance, career roadmap', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorship_sessions', to='programs.program')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorship_sessions', to='programs.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_sessions', to='students.student')),
            ],
            options={
                'verbose_name': 'Mentorship Session',
                'verbose_name_plural': 'Mentorship Sessions',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
    ]
