# Generated by Django 6.1.1 on 2026-09-16 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_location_scholarship_program_scholarship_project_and_more'),
        ('schools', '0003_gradestrength_student_names'),
        ('students', '0002_student_consent_date_student_consent_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Aequs Aerospace Factory Tour, Bosch Manufacturing Visit', max_length=200)),
                ('visit_code', models.CharField(blank=True, help_text='e.g. IV-2026-001 (auto-generated)', max_length=50, unique=True)),
                ('company_name', models.CharField(help_text='e.g. Aequs Aerospace SEZ, Bosch India, Infosys Hubli', max_length=200)),
                ('location', models.CharField(default='Belagavi SEZ, Karnataka', max_length=200)),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('attendee_count', models.PositiveIntegerField(default=0)),
                ('transport_details', models.CharField(blank=True, max_length=255)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_visits', to='programs.program')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_visits', to='programs.project')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industry_visits', to='schools.school')),
                ('students', models.ManyToManyField(blank=True, related_name='industry_visits', to='students.student')),
            ],
            options={
                'verbose_name': 'Industry Visit',
                'verbose_name_plural': 'Industry Visits',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
