# Generated by Django 6.1.1 on 2026-09-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_industryvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='category',
        ),
    ]
