# Generated by Django 6.1.1 on 2026-10-04 02:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_remove_program_category'),
        ('schools', '0003_gradestrength_student_names'),
        ('students', '0002_student_consent_date_student_consent_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikePropenScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, help_text='e.g. MPS-2026-001', max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, default='Other', max_length=20)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('grade_level', models.CharField(default='Class 10', max_length=50)),
                ('academic_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Academic % or aggregate score', max_digits=5)),
                ('annual_family_income', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual family income in INR', max_digits=12)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('statement_of_purpose', models.TextField(blank=True, help_text='Academic aspirations, leadership, or hardship statement')),
                ('scholarship_amount', models.DecimalField(decimal_places=2, default=25000.0, help_text='Sanctioned award amount in INR', max_digits=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Application Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('AWARDED', 'Awarded / Sanctioned'), ('DISBURSED', 'Disbursed'), ('REJECTED', 'Rejected / Ineligible')], default='SUBMITTED', max_length=30)),
                ('academic_year', models.CharField(default='2026-27', max_length=20)),
                ('application_date', models.DateField(default=django.utils.timezone.localdate)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mike_propen_applications', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mike_propen_applications', to='students.student')),
            ],
            options={
                'verbose_name': 'Mike Propen Scholarship Application',
                'verbose_name_plural': 'Mike Propen Scholarship Applications',
                'ordering': ['-application_date', '-created_at'],
            },
        ),
    ]
