# Generated by Django 6.0.4 on 2026-08-10 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('BOOK', 'Books'), ('WORKBOOK', 'Workbook'), ('STUDY_KIT', 'Study Kit'), ('LAPTOP', 'Laptop'), ('INTERNSHIP', 'Internship')], max_length=30)),
                ('academic_year', models.CharField(max_length=20)),
                ('eligible', models.BooleanField(default=False)),
                ('selection_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_records', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'benefit_type', 'academic_year')},
            },
        ),
    ]
