# Generated by Django 6.0.4 on 2026-08-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Example: 2025-26', max_length=20)),
                ('class_or_course', models.CharField(help_text='Example: Class 10, 2nd PUC, Degree', max_length=50)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_class', models.CharField(blank=True, max_length=50)),
                ('promotion_status', models.CharField(blank=True, max_length=50)),
                ('transfer_school', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year'],
            },
        ),
    ]
