# Generated by Django 6.0.4 on 2026-08-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='class_or_course',
            field=models.CharField(help_text='Example: Class 10, 2nd PUC, 3rd Year Diploma', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='academicrecord',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'class_or_course'), name='unique_student_academic_course_year'),
        ),
    ]
