# Generated by Django 6.0.4 on 2026-08-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicrecord_class_or_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='class_or_course',
            field=models.CharField(help_text='Example: Class 10, BE 2nd year, Diploma 3rd year', max_length=50),
        ),
    ]
