# Generated by Django 6.0.4 on 2026-08-24 07:18

import academics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academicrecord_class_or_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='academic_year',
            field=models.CharField(default=academics.models.get_current_academic_year, help_text='Example: 2026-27', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='class_or_course',
            field=models.CharField(help_text='Example: Class 10, 2nd PUC, 3rd Year Diploma', max_length=50),
        ),
    ]
