# Generated by Django 6.0.4 on 2026-08-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_academicrecord_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('SCHOOL', 'School'), ('PUC', 'Pre-University'), ('DIPLOMA', 'Diploma'), ('DEGREE', 'Degree'), ('PG', 'Post Graduation'), ('PROFESSIONAL', 'Professional')], max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
    ]
