# Generated by Django 6.1.1 on 2026-09-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_coursemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='e.g. Mathematics, Science, English, Regional Language, Social Science', max_length=100)),
                ('exam_type', models.CharField(choices=[('UNIT_TEST', 'Unit Test'), ('MIDTERM', 'Midterm Examination'), ('ANNUAL', 'Annual Examination'), ('DIAGNOSTIC', 'Diagnostic Assessment')], default='ANNUAL', max_length=30)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, help_text='e.g. A+, A, B, C, D', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('academic_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='academics.academicrecord')),
            ],
            options={
                'ordering': ['subject_name', 'exam_type'],
                'unique_together': {('academic_record', 'subject_name', 'exam_type')},
            },
        ),
    ]
